### ISSUE TITLE
IndexError: index 1 is out of bounds for axis 1 with size 1

### ISSUE THREAD

**Issue by xdTAGCLAN** [computervisioneng/automatic-number-plate-recognition-python-yolov8#7]
When executing main.py, it works for a while (0: 384x640 1 license_plate, 133.0ms
Speed: 4.5ms preprocess, 133.0ms inference, 2.5ms postprocess per image at shape (1, 3, 640, 640)

But eventually I get this error:
0: 384x640 (no detections), 90.0ms
Speed: 3.5ms preprocess, 90.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)
Traceback (most recent call last):
  File "C:\Users\.....\Downloads\Plate Recognizer\main.py", line 39, in <module>
    track_ids = mot_tracker.update(np.asarray(detections_))
  File "C:\Users\.....\Downloads\Plate Recognizer\sort\sort.py", line 232, in update
    matched, unmatched_dets, unmatched_trks = associate_detections_to_trackers(dets,trks, self.iou_threshold)
  File "C:\Users\.....\Downloads\Plate Recognizer\sort\sort.py", line 163, in associate_detections_to_trackers
    iou_matrix = iou_batch(detections, trackers)
  File "C:\Users\.....\Downloads\Plate Recognizer\sort\sort.py", line 55, in iou_batch
    yy1 = np.maximum(bb_test[..., 1], bb_gt[..., 1])
IndexError: index 1 is out of bounds for axis 1 with size 1

**Comment by computervisioneng** [comment]
Does it only happen when you detect a single license plate?

**Comment by fitratgulmamadov** [comment]
Speed: 1.2ms preprocess, 54.9ms inference, 0.5ms postprocess per image at shape (1, 3, 640, 640)
Traceback (most recent call last):
  File "/home/fitrat/Desktop/automatic-number-plate-recognition-python-yolov8/main.py", line 39, in <module>
    track_ids = mot_tracker.update(np.asarray(detections_))
  File "/home/fitrat/Desktop/automatic-number-plate-recognition-python-yolov8/sort/sort.py", line 232, in update
    matched, unmatched_dets, unmatched_trks = associate_detections_to_trackers(dets,trks, self.iou_threshold)
  File "/home/fitrat/Desktop/automatic-number-plate-recognition-python-yolov8/sort/sort.py", line 163, in associate_detections_to_trackers
    iou_matrix = iou_batch(detections, trackers)
  File "/home/fitrat/Desktop/automatic-number-plate-recognition-python-yolov8/sort/sort.py", line 55, in iou_batch
    yy1 = np.maximum(bb_test[..., 1], bb_gt[..., 1])
IndexError: index 1 is out of bounds for axis 1 with size 1




++++ 
The same problem, i don`t know what step i passed wrong
++++

**Comment by educastelo** [comment]
I've got the same error when I try to process a video different from "sample.mp4"

0: 384x640 1 license_plate, 4.1ms
Speed: 1.6ms preprocess, 4.1ms inference, 4.9ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 (no detections), 4.5ms
Speed: 1.2ms preprocess, 4.5ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)
Traceback (most recent call last):
  File "/home/eduardo/projects/dev/automatic-number-plate-recognition-python-yolov8/main.py", line 39, in <module>
    track_ids = mot_tracker.update(np.asarray(detections_))
  File "/home/eduardo/projects/dev/automatic-number-plate-recognition-python-yolov8/sort/sort.py", line 232, in update
    matched, unmatched_dets, unmatched_trks = associate_detections_to_trackers(dets,trks, self.iou_threshold)
  File "/home/eduardo/projects/dev/automatic-number-plate-recognition-python-yolov8/sort/sort.py", line 163, in associate_detections_to_trackers
    iou_matrix = iou_batch(detections, trackers)
  File "/home/eduardo/projects/dev/automatic-number-plate-recognition-python-yolov8/sort/sort.py", line 55, in iou_batch
    yy1 = np.maximum(bb_test[..., 1], bb_gt[..., 1])
IndexError: index 1 is out of bounds for axis 1 with size 1
